name: Ubuntu-20.04

on:
  push:
    branches:
      - main
  pull_request:

env:
  BUILD_TYPE: Release

jobs:
  unit_test:
    runs-on: ubuntu-20.04
    env:
      NUM_THREADS: 1
    steps:

    - name: Clone Repository
      uses: actions/checkout@v2
      with:
        submodules: recursive
        ssh-key: ${{secrets.SSH_KEY_FOR_ACTIONS}}
        persist-credentials: false

    - name: Create Build Environment
      shell: bash
      run: |
        sudo apt-get install -y libgflags-dev libtbb-dev
        cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DINDEX_BENCH_BUILD_TESTS=on -DINDEX_BENCH_TEST_THREAD_NUM=2 -DINDEX_BENCH_BUILD_OPEN_BWTREE=on -DINDEX_BENCH_BUILD_MASSTREE=on -DINDEX_BENCH_BUILD_PTREE=on

    - name: Build
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --parallel 2 --config $BUILD_TYPE

    - name: Test
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: ctest -C $BUILD_TYPE --output-on-failure
