name: Ubuntu-20.04

on:
  push:
    branches:
      - main
  pull_request:

env:
  BUILD_TYPE: Release

jobs:
  unit_test:
    runs-on: ubuntu-20.04
    env:
      NUM_THREADS: 2
    steps:

    - name: Clone Repository
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Create Build Environment
      shell: bash
      run: |
        sudo apt-get install -y libgflags-dev
        cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DINDEX_BENCH_BUILD_TESTS=ON -DINDEX_BENCH_TEST_THREAD_NUM=${NUM_THREADS}

    - name: Build
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --parallel ${NUM_THREADS} --config ${BUILD_TYPE}

    - name: Test
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${BUILD_TYPE} --output-on-failure
