# name: Unit Tests

# on:
#   push:
#     branches:
#       - main
#   pull_request:

# env:
#   BUILD_TYPE: Release

# jobs:
#   unit_test:
#     runs-on: ubuntu-20.04
#     steps:

#     - name: Clone Main Repository
#       uses: actions/checkout@v2

#     - name: Clone Submodule - glog
#       uses: actions/checkout@v2
#       with:
#         repository: google/glog
#         path: external/glog

#     - name: Clone Submodule - GoogleTest
#       uses: actions/checkout@v2
#       with:
#         repository: google/googletest
#         path: external/googletest

#     - name: Create Build Environment
#       shell: bash
#       run: |
#         sudo apt-get install -y build-essential cmake libgflags-dev
#         cmake -E make_directory ${{github.workspace}}/build

#     - name: Configure CMake
#       shell: bash
#       working-directory: ${{github.workspace}}/build
#       run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_TESTS=on

#     - name: Build
#       shell: bash
#       working-directory: ${{github.workspace}}/build
#       run: cmake --build . --parallel 2 --config $BUILD_TYPE

#     - name: Test
#       shell: bash
#       working-directory: ${{github.workspace}}/build
#       run: ctest -C $BUILD_TYPE
